// src/App.vue
<script setup lang="ts">
  import Sidebar from "~/components/shared/Sidebar.vue"
  import Home from "~/app/Home.vue"
  import Screens from "~/app/Screens.vue";
  import Devices from "~/app/Devices.vue";
  import Accounts from "~/app/Accounts.vue";
  import Settings from "~/app/Settings.vue";

  import { useAppStore } from "~/store/app";
  const app = useAppStore()
</script>

<template>
  <main class="w-screen h-screen flex flex-row overflow-hidden">
    <Sidebar />
    <Home v-show="app.screen == 'home'" />
    <Screens v-show="app.screen == 'screens'" />
    <Devices v-show="app.screen == 'devices'" />
    <Accounts v-show="app.screen == 'accounts'" />
    <Settings v-show="app.screen == 'settings'" />
  </main>
</template>

// src/app/index.tsx
import { Sidebar } from "~/components/sidebar";
import { useMainStore } from "~/store/main";
import { Home } from "~/app/home";
import { Screens } from "~/app/screens";
import { Devices } from "~/app/devices";
import { Accounts } from "~/app/accounts";
import { Settings } from "~/app/settings";

function Main() {
  const { screen } = useMainStore();
  return (
    <main className="w-screen h-screen overflow-hidden flex flex-row">
      <Sidebar />
      {screen == "home" && <Home />}
      {screen == "screens" && <Screens />}
      {screen == "devices" && <Devices />}
      {screen == "accounts" && <Accounts />}
      {screen == "settings" && <Settings />}
    </main>
  );
}

export default Main;
